<?php

return [
    "sign_in" => "Login",
    "go_to_login" => "Go to Login",
    "failed" => "No account matching those credentials could be found.",
    "login_to_continue" => "Login to Continue",
    "login_validation_user_required" => "A username or email must be provided.",
    "login_validation_password_required" => "Please enter your account password.",
    "request_password_reset" => "Request Password Reset",
    "send_email" => "Send Email",
    "return_to_login" => "Return to Login",
    "reset_password_title" => "Reset Password",
    "reset_and_sign_in" => "Reset and Sign In",
    "new_password_required" => "Please enter a new password.",
    "validation_email_required" => "A valid email address must be provided to continue.",

    "forgot_password" => [
        "label" => "Forgot Password?",
        "label_help" => "Enter your account email address to receive instructions on resetting your password.",
        "button" => "Recover Account",
    ],

    "reset_password" => [
        "button" => "Reset and Sign In",
    ],

    "two_factor" => [
        "label" => "2-Factor Token",
        "label_help" => "Enter the two-factor token generated by your device.",
        "checkpoint_failed" => "The two-factor authentication token was invalid.",
        "device_checkpoint" => "Device Checkpoint",
        "recovery_code" => "Recovery Code",
        "recovery_code_help" => "Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.",
        "continue" => "Continue",
        "lost_device" => "I have Lost My Device",
        "have_device" => "I Have My Device",
    ],

    "throttle" => "Too many login attempts. Please try again in :seconds seconds.",
    "password_requirements" => "Password must be at least 8 characters in length and should be unique to this site.",
    "2fa_must_be_enabled" => "The administrator has required that 2-Factor Authentication be enabled for your account in order to use the Panel.",
];
